version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: google.golang.org/api
    versions:
    - 0.38.0
    - 0.39.0
    - 0.40.0
    - 0.42.0
    - 0.43.0
    - 0.44.0
