before:
  hooks:
    - go mod download
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    main: ./cmd/smartdevicemanagement_exporter/main.go
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  - binaries:
      - smartdevicemanagement_exporter
    image_templates:
      - "ryancurrah/smartdevicemanagement_exporter:{{ .Tag }}"
      - "ryancurrah/smartdevicemanagement_exporter:v{{ .Major }}"
      - "ryancurrah/smartdevicemanagement_exporter:v{{ .Major }}.{{ .Minor }}"
      - "ryancurrah/smartdevicemanagement_exporter:latest"
